export type Tier = { value: number; label: string };

export const tiers: Tier[] = [
    { value: 0, label: "Unrated" },
    { value: 1, label: "Bronze V" },
    { value: 2, label: "Bronze IV" },
    { value: 3, label: "Bronze III" },
    { value: 4, label: "Bronze II" },
    { value: 5, label: "Bronze I" },
    { value: 6, label: "Silver V" },
    { value: 7, label: "Silver IV" },
    { value: 8, label: "Silver III" },
    { value: 9, label: "Silver II" },
    { value: 10, label: "Silver I" },
    { value: 11, label: "Gold V" },
    { value: 12, label: "Gold IV" },
    { value: 13, label: "Gold III" },
    { value: 14, label: "Gold II" },
    { value: 15, label: "Gold I" },
    { value: 16, label: "Platinum V" },
    { value: 17, label: "Platinum IV" },
    { value: 18, label: "Platinum III" },
    { value: 19, label: "Platinum II" },
    { value: 20, label: "Platinum I" },
    { value: 21, label: "Diamond V" },
    { value: 22, label: "Diamond IV" },
    { value: 23, label: "Diamond III" },
    { value: 24, label: "Diamond II" },
    { value: 25, label: "Diamond I" },
    { value: 26, label: "Ruby V" },
    { value: 27, label: "Ruby IV" },
    { value: 28, label: "Ruby III" },
    { value: 29, label: "Ruby II" },
    { value: 30, label: "Ruby I" },
];

export const marks: Tier[] = [
    { value: 1, label: "Bronze V" },
    { value: 6, label: "Silver V" },
    { value: 11, label: "Gold V" },
    { value: 16, label: "Platinum V" },
    { value: 21, label: "Diamond V" },
    { value: 26, label: "Ruby V" },
]