/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as RegisterImport } from './routes/register'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as CreateImport } from './routes/create'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PracticesIndexImport } from './routes/practices/index'
import { Route as ContestsIndexImport } from './routes/contests/index'
import { Route as RoomsRoomIdImport } from './routes/rooms/$roomId'
import { Route as ProfileHandleImport } from './routes/profile/$handle'
import { Route as PracticesCreateImport } from './routes/practices/create'
import { Route as ContestsContestIdImport } from './routes/contests/$contestId'
import { Route as PracticesPracticeIdRankImport } from './routes/practices/$practiceId/rank'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CreateRoute = CreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PracticesIndexRoute = PracticesIndexImport.update({
  id: '/practices/',
  path: '/practices/',
  getParentRoute: () => rootRoute,
} as any)

const ContestsIndexRoute = ContestsIndexImport.update({
  id: '/contests/',
  path: '/contests/',
  getParentRoute: () => rootRoute,
} as any)

const RoomsRoomIdRoute = RoomsRoomIdImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRoute,
} as any)

const ProfileHandleRoute = ProfileHandleImport.update({
  id: '/profile/$handle',
  path: '/profile/$handle',
  getParentRoute: () => rootRoute,
} as any)

const PracticesCreateRoute = PracticesCreateImport.update({
  id: '/practices/create',
  path: '/practices/create',
  getParentRoute: () => rootRoute,
} as any)

const ContestsContestIdRoute = ContestsContestIdImport.update({
  id: '/contests/$contestId',
  path: '/contests/$contestId',
  getParentRoute: () => rootRoute,
} as any)

const PracticesPracticeIdRankRoute = PracticesPracticeIdRankImport.update({
  id: '/practices/$practiceId/rank',
  path: '/practices/$practiceId/rank',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/contests/$contestId': {
      id: '/contests/$contestId'
      path: '/contests/$contestId'
      fullPath: '/contests/$contestId'
      preLoaderRoute: typeof ContestsContestIdImport
      parentRoute: typeof rootRoute
    }
    '/practices/create': {
      id: '/practices/create'
      path: '/practices/create'
      fullPath: '/practices/create'
      preLoaderRoute: typeof PracticesCreateImport
      parentRoute: typeof rootRoute
    }
    '/profile/$handle': {
      id: '/profile/$handle'
      path: '/profile/$handle'
      fullPath: '/profile/$handle'
      preLoaderRoute: typeof ProfileHandleImport
      parentRoute: typeof rootRoute
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdImport
      parentRoute: typeof rootRoute
    }
    '/contests/': {
      id: '/contests/'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsIndexImport
      parentRoute: typeof rootRoute
    }
    '/practices/': {
      id: '/practices/'
      path: '/practices'
      fullPath: '/practices'
      preLoaderRoute: typeof PracticesIndexImport
      parentRoute: typeof rootRoute
    }
    '/practices/$practiceId/rank': {
      id: '/practices/$practiceId/rank'
      path: '/practices/$practiceId/rank'
      fullPath: '/practices/$practiceId/rank'
      preLoaderRoute: typeof PracticesPracticeIdRankImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/contests/$contestId': typeof ContestsContestIdRoute
  '/practices/create': typeof PracticesCreateRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/contests': typeof ContestsIndexRoute
  '/practices': typeof PracticesIndexRoute
  '/practices/$practiceId/rank': typeof PracticesPracticeIdRankRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/contests/$contestId': typeof ContestsContestIdRoute
  '/practices/create': typeof PracticesCreateRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/contests': typeof ContestsIndexRoute
  '/practices': typeof PracticesIndexRoute
  '/practices/$practiceId/rank': typeof PracticesPracticeIdRankRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/contests/$contestId': typeof ContestsContestIdRoute
  '/practices/create': typeof PracticesCreateRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/contests/': typeof ContestsIndexRoute
  '/practices/': typeof PracticesIndexRoute
  '/practices/$practiceId/rank': typeof PracticesPracticeIdRankRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/create'
    | '/login'
    | '/logout'
    | '/register'
    | '/settings'
    | '/contests/$contestId'
    | '/practices/create'
    | '/profile/$handle'
    | '/rooms/$roomId'
    | '/contests'
    | '/practices'
    | '/practices/$practiceId/rank'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/create'
    | '/login'
    | '/logout'
    | '/register'
    | '/settings'
    | '/contests/$contestId'
    | '/practices/create'
    | '/profile/$handle'
    | '/rooms/$roomId'
    | '/contests'
    | '/practices'
    | '/practices/$practiceId/rank'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/create'
    | '/login'
    | '/logout'
    | '/register'
    | '/settings'
    | '/contests/$contestId'
    | '/practices/create'
    | '/profile/$handle'
    | '/rooms/$roomId'
    | '/contests/'
    | '/practices/'
    | '/practices/$practiceId/rank'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreateRoute: typeof CreateRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ContestsContestIdRoute: typeof ContestsContestIdRoute
  PracticesCreateRoute: typeof PracticesCreateRoute
  ProfileHandleRoute: typeof ProfileHandleRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  ContestsIndexRoute: typeof ContestsIndexRoute
  PracticesIndexRoute: typeof PracticesIndexRoute
  PracticesPracticeIdRankRoute: typeof PracticesPracticeIdRankRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreateRoute: CreateRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ContestsContestIdRoute: ContestsContestIdRoute,
  PracticesCreateRoute: PracticesCreateRoute,
  ProfileHandleRoute: ProfileHandleRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  ContestsIndexRoute: ContestsIndexRoute,
  PracticesIndexRoute: PracticesIndexRoute,
  PracticesPracticeIdRankRoute: PracticesPracticeIdRankRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/create",
        "/login",
        "/logout",
        "/register",
        "/settings",
        "/contests/$contestId",
        "/practices/create",
        "/profile/$handle",
        "/rooms/$roomId",
        "/contests/",
        "/practices/",
        "/practices/$practiceId/rank"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/create": {
      "filePath": "create.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/contests/$contestId": {
      "filePath": "contests/$contestId.tsx"
    },
    "/practices/create": {
      "filePath": "practices/create.tsx"
    },
    "/profile/$handle": {
      "filePath": "profile/$handle.tsx"
    },
    "/rooms/$roomId": {
      "filePath": "rooms/$roomId.tsx"
    },
    "/contests/": {
      "filePath": "contests/index.tsx"
    },
    "/practices/": {
      "filePath": "practices/index.tsx"
    },
    "/practices/$practiceId/rank": {
      "filePath": "practices/$practiceId/rank.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
