"""add minrating maxrating to contest

Revision ID: 00b274b04fe9
Revises: 9e331ef47617
Create Date: 2025-02-04 04:05:26.724310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '00b274b04fe9'
down_revision: Union[str, None] = '9e331ef47617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('min_rating', sa.Integer(), nullable=True))
    op.add_column('contests', sa.Column('max_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contests', 'max_rating')
    op.drop_column('contests', 'min_rating')
    # ### end Alembic commands ###
