"""add practiceset difficulty, desc

Revision ID: 0dbeac95a89d
Revises: 9c5f28997f0a
Create Date: 2025-02-28 17:10:25.931862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dbeac95a89d'
down_revision: Union[str, None] = '9c5f28997f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_sets', sa.Column('desc', sa.String(), nullable=True))
    op.add_column('practice_sets', sa.Column('difficulty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_sets', 'difficulty')
    op.drop_column('practice_sets', 'desc')
    # ### end Alembic commands ###
