"""add mission difficulty

Revision ID: 103b457921ee
Revises: 550dd1d22f9d
Create Date: 2025-02-01 00:37:14.518935

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '103b457921ee'
down_revision: Union[str, None] = '550dd1d22f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_missions', sa.Column('difficulty', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_missions', 'difficulty')
    # ### end Alembic commands ###
