"""add unsolvable missions,next solve missions in player

Revision ID: 1b10836df245
Revises: 6fb5c4fd4ecc
Create Date: 2025-02-16 17:02:56.351094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1b10836df245'
down_revision: Union[str, None] = '6fb5c4fd4ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_players', sa.Column('unsolvable_mission_ids', sa.ARRAY(sa.Integer()), nullable=True,
                                            server_default=sa.text("'{}'")))
    op.add_column('room_players', sa.Column('next_solvable_mission_ids', sa.ARRAY(sa.Integer()), nullable=True,
                                            server_default=sa.text("'{}'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_players', 'next_solvable_mission_ids')
    op.drop_column('room_players', 'unsolvable_mission_ids')
    # ### end Alembic commands ###
