"""add last_solved_at in room

Revision ID: 550dd1d22f9d
Revises: b2739afedac4
Create Date: 2025-01-26 04:55:09.709158

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '550dd1d22f9d'
down_revision: Union[str, None] = 'b2739afedac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('last_solved_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("""
            UPDATE rooms
            SET last_solved_at = COALESCE(
                (SELECT MAX(solved_at) FROM room_missions WHERE room_missions.room_id = rooms.id),
                rooms.created_at
            )
        """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'last_solved_at')
    # ### end Alembic commands ###
