"""add platform to user, room

Revision ID: 620202f31662
Revises: dffba8b9cac0
Create Date: 2025-02-12 19:29:52.248120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '620202f31662'
down_revision: Union[str, None] = 'dffba8b9cac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE platform AS ENUM ('BOJ', 'CODEFORCES')")

    op.add_column('room_missions', sa.Column('platform', sa.Enum('BOJ', 'CODEFORCES', name='platform'), nullable=False,
                                             server_default="BOJ"))
    op.drop_column('room_missions', 'problem_type')
    op.add_column('rooms', sa.Column('platform', sa.Enum('BOJ', 'CODEFORCES', name='platform'), nullable=False,
                                     server_default="BOJ"))
    op.add_column('users', sa.Column('platform', sa.Enum('BOJ', 'CODEFORCES', name='platform'), nullable=False,
                                     server_default="BOJ"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'platform')
    op.drop_column('rooms', 'platform')
    op.add_column('room_missions', sa.Column('problem_type', postgresql.ENUM('BOJ', 'CODEFORCES', name='problemtype'),
                                             autoincrement=False, nullable=False, server_default="BOJ"))
    op.drop_column('room_missions', 'platform')
    # ### end Alembic commands ###
