"""alter owner from user to member

Revision ID: 6fb5c4fd4ecc
Revises: 4337a4bb413a
Create Date: 2025-02-12 21:22:38.828539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb5c4fd4ecc'
down_revision: Union[str, None] = '4337a4bb413a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rooms_owner_id_fkey', 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'members', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key('rooms_owner_id_fkey', 'rooms', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
