"""add is_deleted to practiceset

Revision ID: 7e744707bac4
Revises: fc963b759e33
Create Date: 2025-03-06 03:17:38.608986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7e744707bac4'
down_revision: Union[str, None] = 'fc963b759e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_sets', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_sets', 'is_deleted')
    # ### end Alembic commands ###
