"""fix relation

Revision ID: 9c5f28997f0a
Revises: dae510910c91
Create Date: 2025-02-28 15:54:54.785047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5f28997f0a'
down_revision: Union[str, None] = 'dae510910c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rooms_practice_session_id_fkey', 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'practice_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('practice_session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('rooms_practice_session_id_fkey', 'rooms', 'practice_members', ['practice_session_id'], ['id'])
    # ### end Alembic commands ###
