"""add member performance

Revision ID: 9e331ef47617
Revises: ca6154415556
Create Date: 2025-02-03 18:21:20.508360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e331ef47617'
down_revision: Union[str, None] = 'ca6154415556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest_members', sa.Column('performance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest_members', 'performance')
    # ### end Alembic commands ###
