"""add boardtype to room

Revision ID: a2268f195cf7
Revises: 0dbeac95a89d
Create Date: 2025-02-28 18:21:00.514071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a2268f195cf7'
down_revision: Union[str, None] = '0dbeac95a89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # PostgreSQL에 Enum 타입 생성
    boardtype = sa.Enum('HEXAGON', 'LINEAR', name='boardtype')
    boardtype.create(op.get_bind(), checkfirst=True)

    # 테이블에 컬럼 추가
    op.add_column('rooms', sa.Column('board_type', boardtype, nullable=False, server_default="HEXAGON"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'board_type')
    # ### end Alembic commands ###
