"""add unfreeze_offset_minutes

Revision ID: a870a68c2f20
Revises: 103b457921ee
Create Date: 2025-02-01 02:30:19.535789

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a870a68c2f20'
down_revision: Union[str, None] = '103b457921ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('unfreeze_offset_minutes', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'unfreeze_offset_minutes')
    # ### end Alembic commands ###
