"""empty message

Revision ID: bea406deb1c6
Revises: b74cb7821071
Create Date: 2025-01-19 16:16:52.422801

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bea406deb1c6'
down_revision: Union[str, None] = 'b74cb7821071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='role'), nullable=False,
                                       server_default='MEMBER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'role')
    # ### end Alembic commands ###
