"""add member rating, etc

Revision ID: ca6154415556
Revises: e3c1087c2b0b
Create Date: 2025-02-03 05:05:21.732038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ca6154415556'
down_revision: Union[str, None] = 'e3c1087c2b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest_members', sa.Column('rating_before', sa.Integer(), nullable=True))
    op.add_column('contest_members', sa.Column('rating_after', sa.Integer(), nullable=True))
    op.add_column('contests', sa.Column('is_rated', sa.Boolean(), nullable=True))
    op.add_column('members', sa.Column('rating', sa.Integer(), nullable=True, server_default="1200"))
    op.add_column('room_players', sa.Column('rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_players', 'rank')
    op.drop_column('members', 'rating')
    op.drop_column('contests', 'is_rated')
    op.drop_column('contest_members', 'rating_after')
    op.drop_column('contest_members', 'rating_before')
    # ### end Alembic commands ###
