"""add contest is_started, is_ended, room is_contest_room

Revision ID: e3c1087c2b0b
Revises: a870a68c2f20
Create Date: 2025-02-02 19:17:44.707335

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e3c1087c2b0b'
down_revision: Union[str, None] = 'a870a68c2f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('is_started', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.add_column('contests', sa.Column('is_ended', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.alter_column('room_missions', 'difficulty',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    existing_server_default=sa.text('0'))
    op.add_column('rooms', sa.Column('is_contest_room', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_contest_room')
    op.alter_column('room_missions', 'difficulty',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    existing_server_default=sa.text('0'))
    op.drop_column('contests', 'is_ended')
    op.drop_column('contests', 'is_started')
    # ### end Alembic commands ###
