"""add solved mission count to user

Revision ID: fc963b759e33
Revises: 774b95b69fc6
Create Date: 2025-03-01 16:15:46.129723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fc963b759e33'
down_revision: Union[str, None] = '774b95b69fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('num_solved_missions', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'num_solved_missions')
    # ### end Alembic commands ###
